server:
   port: 8040
spring:
  application:
     name: microservice-config-server
  cloud:
     config:
        server:
           git:
             uri: https://github.com/xlk123xlk/springbootDemo/
             search-paths: config-repo
             username: 
             password:

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/            
             

 