server:
    port: 8113

spring:
    application:
         name: microservice-consumer-movie-ribbon

eureka:
    client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka/
    instance:
         preferIpAddress: true