server:
    port: 8112
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: microservice-provider-user

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/