server:
    port: 8114
spring:
    application:
         name: microservice-consumer-movie-feign

eureka:
    client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka/
    instance:
         preferIpAddress: true    